logging:
  level: INFO
  loggers:
    org.example: DEBUG
    org.hibernate.SQL:
      level: DEBUG

# Database settings.
database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/taskmanagement
  user: admin
  password: test
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  properties:
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.show_sql: true