logging:
  level: INFO
  loggers:
    org.example: DEBUG
    org.hibernate.SQL:
      level: DEBUG

# Database settings.
database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/taskmanagement #local :: jdbc:mysql://localhost:3306/taskmanagement || local docker :: jdbc:mysql://test-mysql:3306/taskmanagement || oci :: 10.0.1.123:3306/
  user: admin #local :: admin || local docker :: root || oci :: root
  password: test # local and local docker :: test || oci :: Test@123
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  properties:
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.show_sql: true